const { model, Schema, mongoose } = require("mongoose");

const EnterpriseSchema = new Schema({
  zip: String,
  type: String,
  decommissioned: String,
  primary_city: String,
  acceptable_cities: String,
  unacceptable_cities: String,
  state: String,
  county: String,
  timezone: String,
  area_codes: String,
  world_region: String,
  country: String,
  approximate_latitude: String,
  approximate_longitude: String,
  population_center_latitude: String,
  population_center_longitude: String,
  polygon_offset_latitude: String,
  polygon_offset_longitude: String,
  internal_point_latitude: String,
  internal_point_longitude: String,
  latitude_min: String,
  latitude_max: String,
  longitude_min: String,
  longitude_max: String,
  area_land: String,
  area_water: String,
  housing_count: String,
  irs_estimated_households: String,
  acs_estimated_households: String,
  population_count: String,
  irs_estimated_population: String,
  acs_estimated_population: String,
  white: String,
  black_or_african_american: String,
  american_indian_or_alaskan_native: String,
  asian: String,
  native_hawaiian_and_other_pacific_islander: String,
  other_race: String,
  two_or_more_races: String,
  hispanic_or_latino: String,
  total_male_population: String,
  total_female_population: String,
  pop_under_10: String,
  pop_10_to_19: String,
  pop_20_to_29: String,
  pop_30_to_39: String,
  pop_40_to_49: String,
  pop_50_to_59: String,
  pop_60_to_69: String,
  pop_70_to_79: String,
  pop_80_plus: String,
  percent_population_in_poverty: String,
  median_earnings_past_year: String,
  median_household_income: String,
  median_gross_rent: String,
  median_home_value: String,
  percent_high_school_graduate: String,
  percent_bachelors_degree: String,
  percent_graduate_degree: String,
  searchDate: Date,
  searchCount: Number,
});

const Enterprise = model("enterprise", EnterpriseSchema);

module.exports = Enterprise;
